version: '3'
services:
  notihub-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - db_maria

  db_maria:
    image: mariadb:10.5.13
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
volumes:
  mysql_data:
